config/routes.rb
ComcardTippspiel::Application.routes.draw do
  resources :scores

  devise_for :users

  resources :teams

  resources :tipps

  resources :spiels

  root :to => 'spiels#index'

end

app/models/spiel.rb
#Encoding: UTF-8

class Spiel < ActiveRecord::Base
  has_many :tipps
  default_scope :order => 'start_at'
  
  def team_a
    Team.find(self.team_a_id).name
  end
  
  def team_b
    Team.find(self.team_b_id).name
  end
  
  def versus
    format "%s vs. %s", self.team_a, self.team_b
  end
  
  def status
    (Time.now >= self.start_at) ? 'Keine Tippabgabe mehr möglich' : format("Spielstart ist am %s",self.start_at.strftime("%d.%m.%Y um %H:%M Uhr"))
  end
  
  def good_choice?(tipp)
    return nil if result.nil? or result.empty?
    tmp = nil 
    
    if tipp == result
      tmp = 'gold' 
    else
      a = Score.parse(tipp)
      b = Score.parse(self.result)
      tmp = 'silver' if (a.a_win && b.a_win) or (a.b_win && b.b_win) or (a.patt && b.patt )
    end
    
    tmp
  end
  
  def average
    tg = self.tipps.count
    ta = self.tipps.sum('team_a_result')
    tb = self.tipps.sum('team_b_result')
    format "%2.1f zu %2.1f",  (ta / tg.to_f), (tb / tg.to_f)  
  end
end

app/controllers/spiels_controller.rb
class SpielsController < ApplicationController
  # GET /spiels
  # GET /spiels.json
  def index
    @spiels = Spiel.all # .where("(start_at + interval '24hours') > now()").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spiels }
    end
  end

  # GET /spiels/1
  # GET /spiels/1.json
  def show
    @spiel = Spiel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spiel }
    end
  end

  # GET /spiels/new
  # GET /spiels/new.json
  def new
    @spiel = Spiel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spiel }
    end
  end

  # GET /spiels/1/edit
  def edit
    @spiel = Spiel.find(params[:id])
  end

  # POST /spiels
  # POST /spiels.json
  def create
    @spiel = Spiel.new(params[:spiel])

    respond_to do |format|
      if @spiel.save
        format.html { redirect_to @spiel, notice: 'Spiel was successfully created.' }
        format.json { render json: @spiel, status: :created, location: @spiel }
      else
        format.html { render action: "new" }
        format.json { render json: @spiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spiels/1
  # PUT /spiels/1.json
  def update
    sucess = true
    Spiel.transaction do
      @spiel = Spiel.find(params[:id])
      
      if params[:spiel][:result]
        sucess = Score.calculate(params[:id], params[:spiel][:result])
      end
      sucess = sucess && @spiel.update_attributes(params[:spiel])
    end
    
    respond_to do |format|
      if sucess
        format.html { redirect_to @spiel, notice: 'Spiel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spiels/1
  # DELETE /spiels/1.json
  def destroy
    @spiel = Spiel.find(params[:id])
    @spiel.destroy

    respond_to do |format|
      format.html { redirect_to spiels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/spiels_helper.rb
#Encoding: UTF-8

module SpielsHelper
end

app/views/spiels/_form.html.erb
  <div class="group">
    <%= f.label :start_at, t("activerecord.attributes.spiel.start_at", :default => "Start at"), :class => :label %>
    <%= f.datetime_select :start_at, :class => 'datetime_select' %>
  </div>

  <div class="group">
    <%= f.label :team_a_id, t("activerecord.attributes.spiel.team_a_id", :default => "Team a"), :class => :label %>
    <%= f.collection_select :team_a_id, Team.all, :id, :name, :class => 'select_field' %>
  </div>

  <div class="group">
    <%= f.label :team_b_id, t("activerecord.attributes.spiel.team_b_id", :default => "Team b"), :class => :label %>
    <%= f.collection_select :team_b_id, Team.all, :id, :name, :class => 'select_field' %>
  </div>

  <div class="group">
    <%= f.label :result, t("activerecord.attributes.spiel.result", :default => "Result"), :class => :label %>
    <%= f.text_field :result, :class => 'text_field' %>
  </div>
  
  <div class="group">
    <%= f.label :ko, t("activerecord.attributes.spiel.ko", :default => "KO Spiel?"), :class => :label %>
    <%= f.check_box :ko, :class => 'checkbox' %>
  </div>
      
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), spiels_path, :class => "text_button_padding link_button" %>
</div>

app/views/spiels/_sidebar.html.erb
<div class="block">
  <h3>Ticker</h3>
  <div class="content">
    <p><b>Beste TeilnehmerINNEN:</b></br>
      </br>
      <% Score.select('user_id, SUM(score) AS total').group('user_id').order('total DESC, user_id').limit(5).each do |score| -%>
        <i><%= nameify(score.user.name) %></i> <%= score.total %> Pkt.</br>
      <% end -%>
    </p>
    <p>Es nehmen momentan <%= User.count %>  Spieler teil.</p>
    <p>Insgesamt wurden <%= Tipp.count %> Tipps abgegeben.</p>
    <p><b>Goldrichtige Tipps:</b> <%= Score.where('score = 3').count %></p>
    <p><b>Richtige Tipps:</b> <%= Score.where('score = 1').count %></p>
  </div>
</div>

app/views/spiels/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", spiels_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_spiel_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_spiel_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Spiel</h2>
    <div class="inner">
      <%= form_for @spiel, :url => spiel_path(@spiel), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/spiels/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to(t('links.spielplan'), spiels_path) %></li>
      <li><%= link_to(t('links.tipps'), tipps_path) %></li>
      <li><%= link_to(t('links.score'), scores_path) %></li>
      <li><%= link_to(t('links.teams'), teams_path) %></li>
      <li><%= link_to("#{t("web-app-theme.new", :default => "New")}", new_spiel_path) if current_user.is_superuser? %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Spiele</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">Dein Tipp</th>
          <th><%= t("activerecord.attributes.spiel.state") %></th>
          <th></th>
          <th><%= t("activerecord.attributes.spiel.match") %></th>
          <th class="last"></th>
        </tr>
        <% @spiels.each do |spiel| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= spiel.start_at > (Time.now + (3600 * 2)).utc ? link_to_new_or_edit_tipp(current_user.id, spiel.id) : link_to('Zu spät', "http://www.rippenspreizer.de/4images/data/media/95/Zu_spaet.jpg", :class=>'button') %></td>
          <td><%= link_to((spiel.result.empty? ? l(spiel.start_at) : spiel.result), spiel_path(spiel)) %></td>
          <td><%= image_tag spiel.team_a + '.png', :style=>'border: 1px solid black' %></td>
          <td><b><%= link_to spiel.versus, spiel_path(spiel) %></b></td>
          <td class='last'><%= image_tag spiel.team_b + '.png', :style=>'border: 1px solid black' %></td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/spiels/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", spiels_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_spiel_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Spiel</h2>
    <div class="inner">
      <%= form_for :spiel, :url => spiels_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/spiels/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to(t('links.spielplan'), spiels_path) %></li>
      <li><%= link_to(t('links.tipps'), tipps_path) %></li>
      <li><%= link_to(t('links.score'), scores_path) %></li>
      <li><%= link_to(t('links.teams'), teams_path) %></li>
      <li><%= link_to("#{t("web-app-theme.new", :default => "New")}", new_spiel_path) if current_user.is_superuser? %></li>
    </ul>
  </div>          
  <div class="content">
    <h2><%= @spiel.versus %></h2>
    <div class="inner">
        <p>
          <b><%= @spiel.status %></b>
        </p>
        <p>
          <b><%= t("activerecord.attributes.spiel.result", :default => t("activerecord.labels.result", :default => "Result")) %>:</b>
          <%= @spiel.result.empty? ? 'Ausstehend' : @spiel.result %>
        </p>
        <p>Im <b>Durchschnitt</b> tippen die Teilnehmer auf ein <b>Endergebnis</b> von <%= @spiel.average%> (<%= @spiel.tipps.count %> abgebene Tipps)</p>
    <h4>Abgegebene Tipps</h2>
      <table class='table'>
        <tr><th class='first'>Spieler</th><th class='last'>Tipp</th></tr>
        <% @spiel.tipps.where('user_id != 1').each do |blk| %>
          <tr <%= "style='background-color: lightblue'" if blk.user_id == current_user.id %>><td><%= blk.user ? nameify(blk.user.name) : "gelöschte Person (##{blk.user_id})" %></td><td><%= blk.small %></td></tr>
        <% end %>
      </table>

      <div class="wat-cf">
        <%= @spiel.start_at > (Time.now + (3600 * 2)).utc ? link_to_new_or_edit_tipp(current_user.id, @spiel.id) : link_to('Zu spät', "http://www.rippenspreizer.de/4images/data/media/95/Zu_spaet.jpg", :class=>'button') %>
      <% if current_user.is_superuser? %>
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_spiel_path(@spiel), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), spiel_path(@spiel), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      <% end %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>