config/routes.rb
ComcardTippspiel::Application.routes.draw do
  resources :scores

  devise_for :users

  resources :teams

  resources :tipps

  resources :spiels

  root :to => 'spiels#index'

end

app/models/tipp.rb
#Encoding: UTF-8
class Tipp < ActiveRecord::Base
  belongs_to :spiel
  belongs_to :user
  
  def small
    format "%s : %s", self.team_a_result, self.team_b_result
  end

  def extra_small
    format "%s:%s", self.team_a_result, self.team_b_result
  end

  
  def team_a_win?
    self.team_a_result > self.team_b_result
  end

  def team_b_win?
    self.team_a_result < self.team_b_result
  end

  def patt?
    self.team_a_result == self.team_b_result
  end
  
  def too_late?
    self.errors.add(:base, 'Zu spät! Es kann nur bis Spielbeginn getippt werden!') unless self.spiel.start_at > (Time.now + (3600 *2)).utc
  end
end

app/controllers/tipps_controller.rb
#Encoding: UTF-8
class TippsController < ApplicationController
  # GET /tipps
  # GET /tipps.json
  def index
    @tipps = Tipp # 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipps }
    end
  end

  # GET /tipps/1
  # GET /tipps/1.json
  def show
    @tipp = Tipp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipp }
    end
  end

  # GET /tipps/new
  # GET /tipps/new.json
  def new
    @tipp = Tipp.new(:spiel_id=>params[:spiel_id], :user_id=>params[:user_id]||current_user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipp }
    end
  end

  # GET /tipps/1/edit
  def edit
    @tipp = Tipp.find(params[:id])
    deny_access!('Zugriff verweigert! Es ist verboten die Tipps anderer Spieler zu manipulieren!') if ! current_user.id == @tipp.user_id and ! current_user.is_superuser?
  end

  # POST /tipps
  # POST /tipps.json
  def create
    @tipp = Tipp.new(params[:tipp])
    @tipp.user_id||= current_user.id
    @tipp.errors.add(:base, 'Bei einem KO Spiel kann nicht auf unentschieden getippt werden!') if @tipp.spiel.ko && @tipp.team_a_result == @tipp.team_b_result

    respond_to do |format|
      if ! @tipp.too_late? && @tipp.errors.empty? && @tipp.save
        format.html { redirect_to @tipp.spiel, notice: 'Tipp was successfully created.' }
        format.json { render json: @tipp, status: :created, location: @tipp }
      else
        format.html { render action: "new" }
        format.json { render json: @tipp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipps/1
  # PUT /tipps/1.json
  def update
    @tipp = Tipp.find(params[:id])
    deny_access!('Zugriff verweigert! Es ist verboten die Tipps anderer Spieler zu manipulieren!') if ! current_user.id == @tipp.user_id and ! current_user.is_superuser?
    @tipp.errors.add(:base, 'Bei einem KO Spiel kann nicht auf unentschieden getippt werden!') if @tipp.spiel.ko && @tipp.team_a_result == @tipp.team_b_result
    # deny_access! unless current_user.id == @tipp.user_id and ! current_user.is_superuser?
    
    respond_to do |format|
      if ! @tipp.too_late? && @tipp.errors.empty? && @tipp.update_attributes(params[:tipp])
        format.html { redirect_to @tipp.spiel, notice: 'Tipp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipps/1
  # DELETE /tipps/1.json
  def destroy
    @tipp = Tipp.find(params[:id])
    @tipp.destroy

    respond_to do |format|
      format.html { redirect_to tipps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tipps_helper.rb
module TippsHelper
end

app/views/tipps/_form.html.erb
<% if @tipp.errors.any? -%>
<div class="flash">
  <div class="message error">
    <% @tipp.errors.each do |type,msg| -%><p><%= msg %></p><% end %>
  </div>
</div>
<% end -%>

<div class="inner">

<% if @tipp.spiel.ko %>
  <div class='flash'>
    <div class="message warning"><br>
      Achtung! Dies ist ein KO Spiel. Man kann nicht auf unentschieden Tippen. Gewertet wird der <b>absolute Endstand</b> des Spiels (nach dem Elfmeterschießen)<br>
    <br>
    </div>
  </div>
<% end -%>

<div class='columns wat-cf'>
  <div class='columns left'>
    <div class='group'>
      <%= f.label @tipp.spiel.team_a, :class=>'label' %>
      <%= image_tag @tipp.spiel.team_a + '.png', :style=>'border: 1px solid black' %>
      <%= f.hidden_field :spiel_id %>
    </div>
    
    <div class="group">
      <%= f.number_field :team_a_result, :class => 'number_field', :size=>4 %>
    </div>
  </div>

  <div class='columns right'>
    <div class='group'>
      <%= f.label @tipp.spiel.team_b, :class=>'label' %>
      <%= image_tag @tipp.spiel.team_b + '.png', :style=>'border: 1px solid black' %>
      <%= f.hidden_field :user_id %>
    </div>
    
    <div class='group'>
      <%= f.number_field :team_b_result, :class => 'number_field', :size=>4 %>
    </div>
  </div>
</div>

<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), tipps_path, :class => "text_button_padding link_button" %>
</div>
</div>

app/views/tipps/_sidebar.html.erb
<div class="block notice">
  <h3>Hinweise</h3>
  <div class="content">
    <p>Alle Tipps können jederzeit geändert werden, bis das Spiel begonnen hat. Hier zählt die eingestellte Spielstartzeit (beim jeweiligen Spiel angezeigt) und die Rechnerinterne Uhr.</p>
  </div>
</div>

app/views/tipps/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to(t('links.spielplan'), spiels_path) %></li>
      <li><%= link_to(t('links.tipps'), tipps_path) %></li>
      <li><%= link_to(t('links.score'), scores_path) %></li>
      <li><%= link_to(t('links.teams'), teams_path) %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Tipp</h2>
    <div class="inner">
      <%= form_for @tipp, :url => tipp_path(@tipp), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/tipps/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to(t('links.spielplan'), spiels_path) %></li>
      <li class="active"><%= link_to(t('links.tipps'), tipps_path) %></li>
      <li><%= link_to(t('links.score'), scores_path) %></li>
      <li><%= link_to(t('links.teams'), teams_path) %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Tipps</h2>
    <div class="inner">
      <table class="table small">
        <tr>             
          <th class="first">Spiel</th>
          <% User.where('is_superuser IS FALSE').order('name').all.each do |usr| %><th><span class="rotate"><small><%= nameify(usr.name) %></small></th><% end -%>
          <th>Spiel</th>
          <th class="last"></th>
        </tr>
        <% Spiel.order('start_at').all.each do |spiel| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= link_to spiel.versus, spiel_path(spiel) %></td>
          <% line = {}; @tipps.where('spiel_id = ?', spiel.id).all.each do |ele| line[ele.user_id] = ele end -%>
          <% User.where('is_superuser IS FALSE').order('name').all.each do |usr| -%>
            <% txt = (line[usr.id] ? line[usr.id].extra_small : '-:-') -%>
            <% html_id = spiel.good_choice?(txt)  -%>
            <td <%= "id='#{html_id}'" if html_id %>><%= (current_user.is_superuser? or current_user.can_activate) ? link_to_new_or_edit_tipp(usr.id, spiel.id,'-:-',true)  : txt%></td>
          <% end -%>
          <td><%= link_to spiel.versus, spiel_path(spiel) %></td>
          <td class="last"></td>
          </tr>          
        <% end -%>
        <tr>             
          <th>Spiel</th>
          <% User.where('is_superuser IS FALSE').order('name').all.each do |usr| %><th><span class="rotate"><small><%= nameify(usr.name) %></small></th><% end -%>
          <th>Spiel</th>
          <th></th>
        </tr>
      </table>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/tipps/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to(t('links.spielplan'), spiels_path) %></li>
      <li><%= link_to(t('links.tipps'), tipps_path) %></li>
      <li><%= link_to(t('links.score'), scores_path) %></li>
      <li><%= link_to(t('links.teams'), teams_path) %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">Dein  Tipp</h2>
    <div class="inner">
      <%= form_for @tipp, :url => tipps_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/tipps/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", tipps_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_tipp_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", tipp_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.tipp.user_id", :default => t("activerecord.labels.user_id", :default => "User")) %>:</b>
          <%= @tipp.user_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.tipp.spiel_id", :default => t("activerecord.labels.spiel_id", :default => "Spiel")) %>:</b>
          <%= @tipp.spiel_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.tipp.team_a_result", :default => t("activerecord.labels.team_a_result", :default => "Team a result")) %>:</b>
          <%= @tipp.team_a_result %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.tipp.team_b_result", :default => t("activerecord.labels.team_b_result", :default => "Team b result")) %>:</b>
          <%= @tipp.team_b_result %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_tipp_path(@tipp), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), tipp_path(@tipp), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>