config/routes.rb
ComcardTippspiel::Application.routes.draw do
  resources :scores

  devise_for :users

  resources :teams

  resources :tipps

  resources :spiels

  root :to => 'spiels#index'

end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :spiel
  
  Result = Struct.new :a_win, :b_win, :patt, :a, :b
  def self.parse(result)
    a, b = result.split(':')
    a = a.to_i
    b = b.to_i
    r = Result.new
    r.a_win = a > b
    r.b_win = b > a
    r.patt = a== b
    r.a = a
    r.b = b
    return r
  end
  
  def self.calculate(spiel_id, result)
    blk =Score.parse(result)
    Score.transaction do
      Score.delete_all(['spiel_id = ?', spiel_id]) # Erstmal alle bisherigen Punkte löschen (immer neu Berechnen)
      Tipp.where('spiel_id = ?', spiel_id).each do |tipp|
        val = new(:spiel_id => spiel_id, :user_id => tipp.user_id)
        
        # Treffer gibt 3 Punkte
        if tipp.team_a_result == blk.a && tipp.team_b_result == blk.b
          val.score = 3
        # richtige Tordifferenz 2 Punkte
#         elsif (tipp.team_a_result - tipp.team_b_result) == (blk.a - blk.b)
#           val.score = 2
        # richtiger Ausgang gibt 1 Punkt
        elsif tipp.team_a_win? && blk.a_win or tipp.team_b_win? && blk.b_win or blk.patt && tipp.patt?
          val.score = 1
        else
          val.score = 0
        end
        val.save!
      end
    end
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  # GET /scores
  # GET /scores.json
  def index
#     @scores = Score.select('user_id, SUM(score) AS total').group('user_id').order('total DESC, user_id')
    @scores = Score.joins('JOIN users u ON u.id = user_id').joins('JOIN teams t ON t.id = u.winner_id').select('user_id, u.name, t.name AS winner, t.loser, SUM(score) AS total').group('user_id, u.name, t.name, t.loser').order('total DESC, u.name')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scores }
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
    @score = Score.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/new
  # GET /scores/new.json
  def new
    @score = Score.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @score = Score.find(params[:id])
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(params[:score])

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render json: @score, status: :created, location: @score }
      else
        format.html { render action: "new" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scores/1
  # PUT /scores/1.json
  def update
    @score = Score.find(params[:id])

    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_sidebar.html.erb
<div class="block notice">
  <h3>Punktevergabe</h3>
  <div class="content">
    <p>Die Punkte errechnen sich wie bisher, wie folgt:</p>
    <p><b>richtiger Spielausgang:</b> 1 Pkt</p>
    <p><b>richtiges Ergebnis:</b> 3 Pkt</p>
    <p>Die Punkte werden automatisch errechnet sobald das Ergebnis eingetragen wird. Das eintragen übernimmt der nicht am Spiel teilnehmende, neutrale und unbestechliche Administrator, die aktuellsten Punkte sollten also in der Regel ab 8 Uhr des ersten Werktages nach Spielende vorliegen.</p>
  </div>
</div>

app/views/scores/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to(t('links.spielplan'), spiels_path) %></li>
      <li><%= link_to(t('links.tipps'), tipps_path) %></li>
      <li class="active"><%= link_to(t('links.score'), scores_path) %></li>
      <li><%= link_to(t('links.teams'), teams_path) %></li>
    </ul>
  </div>          
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Punkte</h2>
    <div class="inner">
      <table class="table pokal">
        <tr>
          <th class="first"><%= t('activerecord.attributes.score.rank') %></th>
          <th><%= t("activerecord.attributes.score.user_id") %></th>
          <th>3er Tipps</th>
          <th>1er Tipps</th>
          <th class="last"><%= t('activerecord.attributes.score.score') %></th>
        </tr> 
        <% last_score = 0; real_rank = 0 -%>
        <% @scores.each_with_index do |score,rank| -%>
        <% real_rank = score.total == last_score ? real_rank : rank -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td><b><%= real_rank+1 %></b></td>
          <td><%= image_tag(score.winner + '.png', :style=>'border: 1px solid black; height: 25px') %><%= image_tag('raus.png', :style=>'height: 31px; z-index: 2; margin-left: -35px;margin-top:-2px; position: absolute') if score.loser == 't' %> <%= nameify(score.name) %></td>
          <td><i><%= Score.where(:score => 3).where(:user_id=>score.user_id).count %></i></td>
          <td><i><%= Score.where(:score => 1).where(:user_id=>score.user_id).count %></i></td>
          <td><b><%= score.total %></b></td>
        </tr>
        <% last_score = score.total -%>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/scores/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", scores_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_score_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Score</h2>
    <div class="inner">
      <%= form_for :score, :url => scores_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>